name: PnP.Core.Admin Continuous Integration Tests

on:
  push:
    branches: [dev]
  schedule:
    - cron: "0 3 * * *"

jobs:
  integration-tests:
    runs-on: self-hosted
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.0.x"
          include-prerelease: false
      - name: Check .NET SDK Version
        run: dotnet --info

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Uncomment TestCommon.Instance.Mocking
        run: |
          sed -i 's|//TestCommon.Instance.Mocking = false;|TestCommon.Instance.Mocking = false;|' SharePoint/{PermissionRequestsTests,SiteManagerTests}.cs
        working-directory: src/sdk/PnP.Core.Admin.Test
      - name: Write config
        env:
          CERTIFICATE_THUMBPRINT: ${{ secrets.CERTIFICATE_THUMBPRINT }}
          TENANT_NAME: ${{ secrets.TENANT_NAME }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          SP_USER: ${{ secrets.SP_USER }}
          SP_PASSWORD: ${{ secrets.SP_PASSWORD }}
        run: |
          cat <<EOF > appsettings.ci.json
          {
            "PnPCore": {
              "DisableTelemetry": "true",
              "HttpRequests": {
                "UserAgent": "NONISV|SharePointPnP|PnPCoreSDK",
                "SharePointRest": {
                  "UseRetryAfterHeader": "false",
                  "MaxRetries": "10",
                  "DelayInSeconds": "3",
                  "UseIncrementalDelay": "true"
                },
                "MicrosoftGraph": {
                  "UseRetryAfterHeader": "true",
                  "MaxRetries": "10",
                  "DelayInSeconds": "3",
                  "UseIncrementalDelay": "true"
                }
              },
              "PnPContext": {
                "GraphFirst": "true",
                "GraphCanUseBeta": "true",
                "GraphAlwaysUseBeta": "false"
              },
              "Credentials": {
                "DefaultConfiguration": "x509Certificate",
                "Configurations": {
                  "UsernamePassword": {
                    "ClientId": "$CLIENT_ID",
                    "TenantId": "$TENANT_ID",
                    "UsernamePassword": {
                        "Username": "$SP_USER",
                        "Password": "$SP_PASSWORD"
                    }
                  },
                  "x509Certificate": {
                    "ClientId": "$CLIENT_ID",
                    "TenantId": "$TENANT_ID",
                    "X509Certificate": {
                      "StoreName": "My",
                      "StoreLocation": "CurrentUser",
                      "ThumbPrint": "$CERTIFICATE_THUMBPRINT",
                    }
                  }
                }
              },
              "Sites": {
                "TestSite": {
                  "SiteUrl": "https://$TENANT_NAME.sharepoint.com/sites/pnpcoresdktestgroup",
                  "AuthenticationProviderName": "UsernamePassword"
                },
                "TestSite_Application": {
                  "SiteUrl": "https://$TENANT_NAME.sharepoint.com/sites/pnpcoresdktestgroup",
                  "AuthenticationProviderName": "x509Certificate"
                },
                "TestSubSite": {
                  "SiteUrl": "https://$TENANT_NAME.sharepoint.com/sites/pnpcoresdktestgroup/subsite",
                  "AuthenticationProviderName": "UsernamePassword"
                },
                "NoGroupTestSite": {
                  "SiteUrl": "https://$TENANT_NAME.sharepoint.com/sites/pnpcoresdktest2",
                  "AuthenticationProviderName": "UsernamePassword"
                },
                "NoGroupTestSite_Application": {
                  "SiteUrl": "https://$TENANT_NAME.sharepoint.com/sites/pnpcoresdktest2",
                  "AuthenticationProviderName": "x509Certificate"
                },
                "ClassicSTS0TestSite": {
                  "SiteUrl": "https://$TENANT_NAME.sharepoint.com/sites/sts0",
                  "AuthenticationProviderName": "UsernamePassword"
                },
                "TenantAdminCenterSite": {
                  "SiteUrl": "https://$TENANT_NAME-admin.sharepoint.com",
                  "AuthenticationProviderName": "UsernamePassword"
                },
                "VivaTopicCenterTestSite": {
                  "SiteUrl": "https://$TENANT_NAME.sharepoint.com/sites/TopicCenter",
                  "AuthenticationProviderName": "UsernamePassword"
                },
                "HomeTestSite": {
                  "SiteUrl": "https://$TENANT_NAME.sharepoint.com",
                  "AuthenticationProviderName": "UsernamePassword"
                }
              }
            },
            "Logging": {
              "LogLevel": {
                "Default": "Trace"
              }
            }
          }
          EOF
        working-directory: src/sdk/PnP.Core.Admin.Test

      - name: Test Integration
        run: |
          dotnet test ./PnP.Core.Admin.Test.csproj --filter "PermissionRequestsTests|SiteManagerTests.SetSiteCollectionAdminsRegularSiteAddOnlyApplicationPermissions_Async" --logger trx --results-directory ./TestResults
        working-directory: src/sdk/PnP.Core.Admin.Test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testresults
          path: |
            **/TestResults/**/*
