name: PnP Core Continuous Integration Tests

on:
  push:
    branches: [dev]

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: dotnet restore
        working-directory: src/sdk
      - name: Build ⚙
        run:  dotnet build --configuration debug --no-restore --verbosity normal 
        working-directory: src/sdk
      - name: Test Integration
        run: dotnet test --filter "PermissionRequestsTests"
        working-directory: src/sdk/PnP.Core.Admin.Test
        
